# Generated by Django 4.1.2 on 2022-10-28 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0002_alter_emailverificationmodel_created_at_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 6, 35, 59, 389382)),
        ),
    ]
